### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by lishiyu005** [xukechun/Vision-Language-Grasping#1]
Dear authors,

Thank you for your awesome work. Can you provide us with pretrained model to test?

Best regards

**Comment by xukechun** [comment]
Hi, 

Thanks for your attention to our work! I have uploaded the pretrained model in [this link](https://drive.google.com/drive/folders/1LCuoXX92X8L9wqJTbVqvskjRhTJrDDay?usp=sharing).

Best,
Kechun Xu

**Comment by ubless607** [comment]
@xukechun Is the uploaded pretrained model trained with CLIP-guided loss or not?
