### ISSUE TITLE
训练细节咨询

### ISSUE THREAD

**Issue by wxz1996** [xukechun/Vision-Language-Grasping#12]
感谢您的开源，想问下关于训练的一些细节：
1. 论文中提到的两阶段训练，跑tran.py的时候，只需要修改--num_obj和--num_episode就行吗，论文里提到的是第一阶段是8/500，第二阶段是15/1500
2. Real-world Experiments请问这部分会开源吗

**Comment by xukechun** [comment]
非常抱歉疏忽了一些issue通知
1. 是的，代码中已经设置好了train schedule
2. real-world experiments的部分代码是基于我们实验室的平台资源，这部分可能难以开源，我可以提供一些实现方法，我们在实物中使用的检测方法为[Openset-RCNN](https://github.com/Yifei-Y/Openset-RCNN), 整体框架基于ros进行通信

**Comment by lihua123456** [comment]
在real-world experiments时，Openset-RCNN用来进行目标检测，请问一下使用哪种算法进行目标物体位姿的识别，在仿真中有用到物体的位姿信息。

**Comment by xukechun** [comment]
Hi, we do not use pose estimation in the real world. It is not a necessary module. We use the object bounding boxes to filter some bad grasps instead.







-----原始邮件-----
发件人:"Little Taylor" ***@***.***>
发送时间:2024-09-27 17:21:14 (星期五)
收件人: xukechun/Vision-Language-Grasping ***@***.***>
抄送: kuko ***@***.***>, Comment ***@***.***>
主题: Re: [xukechun/Vision-Language-Grasping] 训练细节咨询 (Issue #12)






在real-world experiments时，Openset-RCNN用来进行目标检测，请问一下使用哪种算法进行目标物体位姿的识别，在仿真中有用到物体的位姿信息。
