### ISSUE TITLE
当时试图运行训练的python文件

### ISSUE THREAD

**Issue by hanyueling** [xukechun/Vision-Language-Grasping#17]
当我试图训练时，显示在env/environment_sim.py文件中打开“case/”+"temp.txt"时找不到该文件。
![`FJP ~ E)@@RF`C$~ZIIV}H](https://github.com/user-attachments/assets/7d9b61d6-aa2b-4b7e-adab-81cb45a3d567)
请问你知道这个问题怎么解决或者这个文件所在的位置吗？

**Comment by xukechun** [comment]
Hi, this is just a temporary file to record the scenario configuration. You can build a blank .txt file at the beginning.
