### ISSUE TITLE
Warning during the training process

### ISSUE THREAD

**Issue by wngkj** [xukechun/Vision-Language-Grasping#18]
Hello, thank you for your work. I found some warning messages during the network training process. According to my understanding, these warnings may be due to conflicts between autocore, ros, and conda. Will these warnings affect the use of the entire code? How can I solve these problems?

pybullet build time: Oct 19 2024 18:03:51
WARNING - 2024-10-22 11:14:29,922 - rigid_transformations - Failed to import geometry msgs in rigid_transformations.py.
WARNING - 2024-10-22 11:14:29,922 - rigid_transformations - Failed to import ros dependencies in rigid_transforms.py
WARNING - 2024-10-22 11:14:29,922 - rigid_transformations - autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable

**Comment by xukechun** [comment]
Hi, these warnings can be ignored since we don't use ROS in this project.
