### ISSUE TITLE
errors like"b3Printf: assets/simplified_objects/027.urdf:6: cannot find '027/textured_simplified.obj' in any directory in urdf path"

### ISSUE THREAD

**Issue by KiriyamaGK** [xukechun/Vision-Language-Grasping#2]
Hi,very thanks for your sharing of your works,but I met problems when running train.py(so is the test.py),the errors are as follows:

(vilg) PS E:\Vision-Language-Grasping-master> python train.py
pybullet build time: Oct 29 2023 19:55:31
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
starting thread 0
started testThreads thread 0 with threadHandle 00000000000016B0
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
Version = 4.6.0 NVIDIA 532.09
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
b3Printf: Selected demo: Physics Server
starting thread 0
started MotionThreads thread 0 with threadHandle 0000000000001A40
MotionThreadFunc thread started
Creating data logging session: E:\Vision-Language-Grasping-master\logs\2023-11-21-20-28-49-train
-> loaded checkpoint models/graspnet/logs/log_rs/checkpoint.tar (epoch: 18)
b3Printf: b3Warning[C:\Users\KiriyamaGK\AppData\Local\Temp\pip-install-5t6gi7xs\pybullet_acbc5d530e114adc8a5cf828dc4bad46\examples\Importers\ImportURDFDemo\UrdfFindMeshFile.h,102]:

**b3Printf: E:\Vision-Language-Grasping-master\assets\simplified_objects\034.urdf:6: cannot find '034/textured_simplified.obj' in any directory in urdf path**

Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: Could not parse visual element for Link:
Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: _name
Warning: b3Error[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,121]:

Warning: failed to parse link
Traceback (most recent call last):
  File "train.py", line 116, in <module>
    reset = env.add_objects(warmup_num_obj, WORKSPACE_LIMITS)
  File "E:\Vision-Language-Grasping-master\environment_sim.py", line 515, in add_objects
    body_id = pb.loadURDF(
pybullet.error: Cannot load URDF file.
Exception ignored in: <function Environment.__del__ at 0x0000018FD3CD1CA0>
Traceback (most recent call last):
  File "E:\Vision-Language-Grasping-master\environment_sim.py", line 429, in __del__
TypeError: 'NoneType' object is not callable
numActiveThreads = 0
stopping threads
Thread with taskId 0 with handle 0000000000001A40 exiting
Thread TERMINATED
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 with handle 00000000000016B0 exiting
Thread TERMINATED
(vilg) PS E:\Vision-Language-Grasping-master>

**Comment by xukechun** [comment]
Hi, 
did you download the full folder in this [link](https://drive.google.com/drive/folders/1lwMV4QjdR8F4bzcegPP8Tiztgg9UAt_h)? The textured_simplified.obj of 027 and 034 are both available at [027](https://drive.google.com/file/d/1pUOQAKuHdTUgHj_3LL4xHKXDNoFjNjT1/view?usp=drive_link) and [034](https://drive.google.com/file/d/1hI6Ch1h2ShiTrQWtjwenCeqvImgYcrQu/view?usp=drive_link).

Best,
Kechun

**Comment by KiriyamaGK** [comment]
Hi,I think maybe all objects.And I checked the CSDN, maybe the object and the urdf file and the object should be in the same folder?

**Comment by KiriyamaGK** [comment]
Hi,I am so sorry that I haven't installed the full folder.I checked the folder you updated online.Some files seem to have been lost during my downloading.
