### ISSUE TITLE
simplified models

### ISSUE THREAD

**Issue by laynewong** [xukechun/Vision-Language-Grasping#22]
请问您是如何简化graspnet里面的3D models？ 我曾经简化过这些模型然后放到Gazebo中，但是会出现滑动现象。我看到您为它们编写的URDF文件，visual和collision两部分使用了不同的obj文件。您是如何简化它们的呢，您能够提供简化模型相关的代码吗，谢谢！

**Comment by xukechun** [comment]
We simplify the 3D models with the simplification operations in [Meshlab](https://www.meshlab.net/).

**Comment by laynewong** [comment]
> We simplify the 3D models with the simplification operations in [Meshlab](https://www.meshlab.net/).

非常感谢您的回复。我在Meshlab上，通过Filters -> Remeshing,Simplification and Reconstruction -> Simplification: Quadric Edge Collapse Decimation 可以得到textured_simplified.obj文件，但是我不知道如何得到textured_simplified_vhacd.obj文件，您能说一下具体的操作吗, 非常感谢。

**Comment by xukechun** [comment]
_vhacd.obj files are generated by this [tool](https://github.com/harvard-microrobotics/object2urdf).

**Comment by laynewong** [comment]
> _vhacd.obj files are generated by this [tool](https://github.com/harvard-microrobotics/object2urdf).

我的问题终于解决了，非常感谢您耐心地解答。
