### ISSUE TITLE
about the code in scripts/grasp_detector.py

### ISSUE THREAD

**Issue by YukiFan** [xukechun/Vision-Language-Grasping#23]
Thanks for your excellent work， i have a question In line 20 of the scripts/grasp_detector.py file:
 **line 20:       grasp_pcd.points = o3d.utility.Vector3dVector(-points)**
I would like to know why **-points** is used and then input into the graspnet_baseline network?

**Comment by xukechun** [comment]
Thanks for pointing out that. For graspnet, we follow functions in this repo https://github.com/OCRTOC/OCRTOC_software_package/blob/50fceb49f19b89eaeee7dde2840e72a9f432e86d/ocrtoc_perception/src/ocrtoc_perception/perceptor.py#L294-L307. 

BTW, I think directly inputting the raw point cloud is also ok.

**Comment by YukiFan** [comment]
thansk for your reply~
