### ISSUE TITLE
在linux下pybullet，界面无法显示在本地

### ISSUE THREAD

**Issue by huamo555** [xukechun/Vision-Language-Grasping#9]
感谢您出色的工作，我现在在运行您的测试代码时会出现问题，cannot connect to X server  导致界面无法显示在本地，请问这样的问题有解决方案吗?

**Comment by xukechun** [comment]
你好! 请问你运行代码的设备有外接屏幕吗，如果是在没有外接屏幕的服务器运行pybullet会有这个错误，需要安装远程桌面解决，如果是在docker容器内运行，需要将容器内的DISPLAY变量设置成和容器外一致。

**Comment by huamo555** [comment]
感谢您的回复，祝您工作顺利。
